backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/media"
public_folder: "/assets/media"
collections:
  - name: "project"
    label: "Project"
    folder: "src/projects"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Tags", name: "tags", widget: "list", default: ["post"]}
      - { label: "Layout", name: "layout", widget: "string", default: ["project-page.njk"]}
      - { label: "Collaborator", name: "collaborator", widget: "string"}
      - { label: "Dates", name: "dates", widget: "string"}
      - { label: "Context", name: "context", widget: "string"}
      - { label: "Poster Image", name: "image", widget: "image"}
      - { label: "Image caption", name: "imageAlt", widget: "string"}
      - { label: "Text input", name: "text", widget: "markdown"}