backend:
  name: git-gateway
  branch: main

# image storage
media_folder: "public/assets/media"
public_folder: "/assets/media"

publish_mode: editorial_workflow # Enable editorial workflow 

collections:
  - name: "project"
    label: "Project"
    folder: "src/projects"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", default: ["project"], required: false }
      - { label: "Collaborator", name: "collaborator", widget: "string", required: false }
      - { label: "Dates", name: "dates", widget: "string", required: false }
      - { label: "Context", name: "context", widget: "string", required: false }
      - { label: "Poster Image", name: "image", widget: "image", required: false }
      - { label: "Image caption", name: "imageAlt", widget: "string", required: false }
      - { label: "Template", name: "template", widget: "hidden", default: "page"}
      - label: "Content Blocks"
        name: "content_blocks"
        widget: "list"
        types:
          - label: "Section Heading"
            name: "section_heading"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "markdown" }
          - label: "Text Block"
            name: "text_block"
            widget: "object"
            fields:
              - { label: "Text", name: "text", widget: "markdown" }
          - label: "Image Block"
            name: "image_block"
            widget: "object"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Image Caption", name: "caption", widget: "string" }
          - label: "Gallery Block"
            name: "gallery_block"
            widget: "list"
            types:
              - label: "Gallery Image"
                name: "gallery_image"
                widget: "object"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Image Caption", name: "caption", widget: "string" }
