backend:
  name: git-gateway
  branch: main

# image storage
media_folder: "public/assets/media"
public_folder: "/assets/media"

publish_mode: editorial_workflow # Enable editorial workflow 

collections:
  - name: "project"
    label: "Project"
    folder: "src/projects"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Tags", name: "tags", widget: "list", default: ["project"]}
      - { label: "Collaborator", name: "collaborator", widget: "string"}
      - { label: "Dates", name: "dates", widget: "string"}
      - { label: "Context", name: "context", widget: "string"}
      - { label: "Poster Image", name: "image", widget: "image"}
      - { label: "Image caption", name: "imageAlt", widget: "string"}
      - { label: "Text input", name: "body", widget: "markdown"}
      - label: "Content Blocks"
        name: "content_blocks"
        widget: "list"
        types:
          - label: "Text Block"
            name: "text_block"
            widget: "object"
            fields:
              - label: "Text"
                name: "text"
                widget: "markdown"
          - label: "Image Block"
            name: "image_block"
            widget: "object"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
